### ISSUE TITLE
Excellent repo

### ISSUE THREAD

**Issue by KainingYing** [yeliudev/nncore#1]
你好，这个codebase的设计逻辑和feature与mmcv相比有什么区别以及优势？

**Comment by yeliudev** [comment]
这里的一些代码（nncore.Engine, nncore.ProgressBar等等）跟早期的mmcv是很相似的，只是加上了一些改进的细节。后面补充的模块（nncore.nn, nncore.utils）也是一些常用的工具，可能mmcv里没有。谈不上有什么明显优势，只是适合我自己的实验罢了😂

**Comment by KainingYing** [comment]
哈哈，仰望大佬，看了你的仓库，项目经验真丰富，还有你的工作也很solid，继续加油

**Comment by yeliudev** [comment]
谢谢，一起加油哈哈哈

**Comment by KainingYing** [comment]
再麻烦问一下，我刚接触HOI-D这个方向，请问有哪些好的codebase可以学习的，有没有像mmdet这样易拓展的库呀，谢谢了

**Comment by yeliudev** [comment]
这个方向的code比较杂，没有一个统一的codebase。可以考虑看下https://github.com/zhihou7/HOI-CL, 我没细看过代码，但这几篇工作都很不错。

**Comment by KainingYing** [comment]
@yeliudev 十分感谢

**Comment by yeliudev** [comment]
不客气😄

**Comment by GuangtaoLyu** [comment]
感谢作者开源的代码和非常好的工作（UMT，NNCore）。
从UMT过来的， https://github.com/TencentARC/UMT ，关于怎么把NNCore引入到自己的工作中，这个有没有什么例子，或者一些参考啊？我看给的文档主要是是介绍API的，有没有一些别的参考。之前大多数时候是自己写的一些代码，没有封装的这么好，之前想自己搞个这种库，没搞出来，看到作者这个，确实很佩服。但是这种封装的好的，一时半会儿改不动。 
有没有什么别的参考。能参考MMSegmentation吗？这个之前接触过一点。UMT看起来一时半会儿改不动。
比如我想改模型，自己搭一些模块该怎么搞？都改些哪里？
万分感谢。

**Comment by yeliudev** [comment]
Many thanks for your interest in this work! In fact, this library was originally developed for my own use. Some functionalities are based on `mmcv` and `fvcore`. Recently, a new project called `mmengine` was released with plenty of new features. I strongly recommend using this library instead, as it can provide much more documents and use cases.

**Comment by GuangtaoLyu** [comment]
> Many thanks for your interest in this work! In fact, this library was originally developed for my own use. Some functionalities are based on `mmcv` and `fvcore`. Recently, a new project called `mmengine` was released with plenty of new features. I strongly recommend using this library instead, as it can provide much more documents and use cases.

Thank you. I will try it.
