### ISSUE TITLE
Import Error in nncore, "cannot import name '_is_namedtuple' from 'torch.nn.parallel.scatter_gather' "

### ISSUE THREAD

**Issue by Hou9612** [yeliudev/nncore#3]
Hello,

Thanks for this wonderful work! When I train UMT (CVPR 2022 UMT: Unified Multi-modal Transformers for Joint Video Moment Retrieval and Highlight Detection), an error raised:

<img width="1170" alt="image" src="https://github.com/yeliudev/nncore/assets/49936825/498bd4dc-06ad-4840-b7c1-1209e436915f">

In my environment, torch version is 1.11.0, nncore version is 0.3.8, both of them meet the requirement in the requirement.txt in UMT, so how to solve this problem?

**Comment by yeliudev** [comment]
Hi @Hou9612, could you please try using the exact version as follows?

- CUDA 11.5.0
- CUDNN 8.3.2.44
- Python 3.10.0
- PyTorch 1.11.0
- NNCore 0.3.6

**Comment by Hou9612** [comment]
> Hi @Hou9612, could you please try using the exact version as follows?
> 
> * CUDA 11.5.0
> * CUDNN 8.3.2.44
> * Python 3.10.0
> * PyTorch 1.11.0
> * NNCore 0.3.6

@yeliudev I change the version of NNCore to 0.3.6, then the code of training UMT can be run well. Thanks very much!
